### ISSUE TITLE
Variables give an error

### ISSUE THREAD

**Issue by ViTuDia** [groepl/Obsidian-Templates#14]
The variables {{date}} {{time}} in the front matter give an error. Looks like that {{date}} {{time}} does not need to be mentioned.

**Comment by groepl** [comment]
Did you activate the Obsidian core plugin "Templates"?

<img width="768" alt="image" src="https://github.com/groepl/Obsidian-Templates/assets/114583103/1f17b61a-e3ae-413e-8721-6787f3f37311">

The {{date}} {{time}} will automatically be inserted when using "Insert template" from the menu. More about: https://help.obsidian.md/Plugins/Templates
