### ISSUE TITLE
Summary/Question/Quotes should be Callouts

### ISSUE THREAD

**Issue by NobleUplift** [groepl/Obsidian-Templates#17]
For the Book Summary: https://github.com/groepl/Obsidian-Templates/blob/main/Templates/Book%20Template.md

It should be a callout: https://help.obsidian.md/Editing+and+formatting/Callouts

Since this is an officially supported field:

```
Abstract
Aliases: summary, tldr
```

Similarly, the Question and Quote templates should use their appropriate callouts since this is default Obsidian functionality.

**Comment by groepl** [comment]
Great idea. 

I've just changed "Summary" to a callout formatting.
