### ISSUE TITLE
Inconsistent usage of `type/tool` and `type/receipe`

### ISSUE THREAD

**Issue by dsiu** [groepl/Obsidian-Templates#20]
In `How to use Link`, `3_Permanent Notes` folder has documents with `type/tool` or `type/receipe` (among other types) whereas in `Zettelkasten - Ontology Map`, `type/tool` and `type/receipe` are under `4_References` folder.

![](https://raw.githubusercontent.com/groepl/Obsidian-Templates/refs/heads/main/Visuals/Linking_with_Templates.png)

![](https://raw.githubusercontent.com/groepl/Obsidian-Templates/refs/heads/main/Visuals/Zettelkasten_Ontology.png)

**Comment by groepl** [comment]
Thank you for your hint. - We now have an update for the diagrams and templates as well.
