### ISSUE TITLE
Composed tags

### ISSUE THREAD

**Issue by robsonsobral** [groepl/Obsidian-Templates#5]
Hi! Thank you for sharing!

Can you, please, add some explanation on how to use the tags with prefixes?

Thank you!

**Comment by robsonsobral** [comment]
A link to https://help.obsidian.md/Plugins/Tags#Nested+tags would be good!

**Comment by groepl** [comment]
Thank you for providing yout hint about using Nested Tags. I added the link to the FAQ at https://github.com/groepl/Obsidian-Templates/blob/main/README.md
