### ISSUE TITLE
`date` and `read` on Books

### ISSUE THREAD

**Issue by robsonsobral** [groepl/Obsidian-Templates#6]
Please, what's the use for the `date` and `read` on `Book Template.md`?

Thank you!

**Comment by groepl** [comment]
Before switching to Obsidian I've had a "Reading list" at "Goodreads". To tranfer this list to Obsidian I use:

rating: from useful to useless
date: when I bought the book
read: when I finished reading

I have a DataView query showing the book per year:

```
```dataview 
TABLE WITHOUT ID
	("![|100](" + cover_url + ")") as Cover,
	file.link AS Book,
	author AS Author, 
	total_page AS "Pages", 
	rating AS Rating
FROM "4_Bibliographical Notes" 
WHERE read = 2023
SORT file.name 
``` 
```
